---
abstract: 'Catalyst UI for the ClinStudyWeb database'
author:
  - 'Tim F. Rayner <tfrayner@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::DBIx::Class: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ClinStudy-Web
no_index:
  directory:
    - inc
    - t
recommends:
  Bio::MAGETAB: 1.1
  LWP::UserAgent: 0
  Term::ReadKey: 0
requires:
  Catalyst::Action::RenderView: 0.08
  Catalyst::Authentication::Store::DBIx::Class: 0.104
  Catalyst::Controller::HTML::FormFu: 0.06001
  Catalyst::Plugin::Authentication: 0.10007
  Catalyst::Plugin::Authorization::ACL: 0.08
  Catalyst::Plugin::Authorization::Roles: 0.05
  Catalyst::Plugin::ConfigLoader: 0.20
  Catalyst::Plugin::Session: 0.19
  Catalyst::Plugin::Session::State::Cookie: 0.09
  Catalyst::Plugin::Session::Store::FastMmap: 0.05
  Catalyst::Plugin::Static::Simple: 0.20
  Catalyst::Runtime: 5.71
  Config::YAML: 1.42
  DBD::mysql: 4.005
  DBIx::Class: 0.08010
  DBIx::Class::Journal: 0.900200
  Digest::SHA1: 2.11
  HTML::FormFu: 0.08002
  HTML::FormFu::Model::DBIC: 0.08002
  Regexp::Common: 2.122
  Template: 2.19
  XML::LibXML: 1.7.0
  XML::Simple: 2.18
  parent: 0.221
  perl: 5.8.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.2
