package CIMR::BloodDB::ExpCtBiochemConcat;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("exp_ct_biochem_concat");
__PACKAGE__->add_columns(
  "hospno",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 24 },
  "resdate",
  {
    data_type => "timestamp",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "restime",
  {
    data_type => "timestamp",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "acr",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "acth",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "albumin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "aldosterone",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "alp",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "alt",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "amylase",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "bicarb",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "bilirubin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "calcium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "chol_hdl_ratio",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "cholesterol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "ciclosporin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "corrected_calcium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "cortisol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "creatinine",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "creatinineclearance",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "crp",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "deletedyn",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "dheasulphate",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "ferritin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "fsh",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "gfr",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "glucose",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "growthhormone",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "hba1c",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "hdl_cholesterol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "igf",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "lactate",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "ldl_cholesterol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "lh",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "lipase",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "magnesium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "oestradiol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "osmolality",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "phosphate",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "potassium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "prolactin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "pth",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "pthpmol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "red_cell_folate",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "renin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "rowinsertdatetime",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "saturation",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "serum_iron",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "sirolimus",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "sodium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "specimenid",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "t3",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "t4",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "tacrolimus",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "testosterone",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "total_ck",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "transferrin",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "triglyceride",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "tsh",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urea",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "uric_acid",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urine5hiaa",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urinefreecortisol",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urineosmolality",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urinepotassium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urinesodium",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "urinevma",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "vitaminb12",
  { data_type => "char", default_value => undef, is_nullable => 1, size => 510 },
  "table_id",
  {
    data_type => "integer",
    default_value => undef,
    is_nullable => 0,
    size => 20,
  },
);
__PACKAGE__->set_primary_key("table_id");


# Created by DBIx::Class::Schema::Loader v0.04006 @ 2010-02-09 10:32:21
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:q6d+cB/Fek1BMq4RBjyn+w


# You can replace this text with custom content, and it will be preserved on regeneration
1;
