---
schema_class: ClinStudy::ORM

fixture_sets:
  patient:
    - Patient:
      -
        - id
        - trial_id
        - entry_date
        - firstname
        - surname
      -
        - 1
        - 100
        - 2008-01-01
        - John
        - Smith
      -
        - 2
        - 101
        - 2009-10-23
        - Jolly
        - Roger
    - Visit:
      -
        - patient_id
        - date
      -
        - 1
        - 2009-10-10
      -
        - 1
        - 2009-10-11
      -
        - 2
        - 2008-01-01

    - AdverseEvent:
      -
        - patient_id
        - start_date
        - type
      -
        - 1
        - 2008-01-19
        - rejection
#    Assay:
#    AssayBatch:
#    AssayQcValue:
#    Channel:
    - Comorbidity:
      -
        - patient_id
        - condition_name
      -
        - 2
        - Angina
    - ControlledVocab:
      -
        - id
        - category
        - value
        - accession
      -
        - 1
        - DiagnosisCondition
        - Systemic Lupus Erythematosus
        - CV1
      -
        - 2
        - DiseaseEvent
        - Relapse
        - CV2
      -
        - 3
        - DrugType
        - immunosuppressant
        - CV3
      -
        - 4
        - DrugLocale
        - in clinic
        - CV4
      -
        - 5
        - PatientGroupBasis
        - gene expression study
        - CV5
      -
        - 6
        - PatientGroup
        - CD6
        - CV1
      -
        - 7
        - PriorGroup
        - vaccination
        - CV7
    - Diagnosis:
      -
        - patient_id
        - condition_name_id
      -
        - 2
        - 1
    - DiseaseEvent:
      -
        - patient_id
        - type_id
        - start_date
      -
        - 1
        - 2
        - 2007-02-03
    - Drug:
      -
        - id
        - name
        - type_id
        - locale_id
      -
        - 1
        - Prednisolone
        - 3
        - 4
    - EmergentGroup:
      -
        - id
        - basis_id
        - type_id
        - name
      -
        - 1
        - 5
        - 6
        - 8.1

    - PriorGroup:
      -
        - id
        - type_id
        - name
      -
        - 1
        - 7
        - V1