package ClinStudy::ORM::Transplant;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("transplant");
__PACKAGE__->add_columns(
  "id",
  { data_type => "INT", default_value => undef, is_nullable => 0, size => 11 },
  "hospitalisation_id",
  { data_type => "INT", default_value => undef, is_nullable => 0, size => 11 },
  "date",
  { data_type => "DATE", default_value => undef, is_nullable => 1, size => 10 },
  "number",
  { data_type => "INT", default_value => undef, is_nullable => 1, size => 6 },
  "sensitisation_status_id",
  { data_type => "INT", default_value => undef, is_nullable => 1, size => 11 },
  "recip_cmv",
  { data_type => "TINYINT", default_value => undef, is_nullable => 1, size => 1 },
  "days_delayed_function",
  { data_type => "INT", default_value => undef, is_nullable => 1, size => 6 },
  "organ_type_id",
  { data_type => "INT", default_value => undef, is_nullable => 0, size => 11 },
  "mins_cold_ischaemic",
  { data_type => "INT", default_value => undef, is_nullable => 1, size => 6 },
  "reperfusion_quality_id",
  { data_type => "INT", default_value => undef, is_nullable => 1, size => 11 },
  "hla_mismatch",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => 255,
  },
  "donor_type_id",
  { data_type => "INT", default_value => undef, is_nullable => 0, size => 11 },
  "donor_age",
  { data_type => "INT", default_value => undef, is_nullable => 1, size => 3 },
  "donor_cause_of_death",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => 255,
  },
  "donor_cmv",
  { data_type => "TINYINT", default_value => undef, is_nullable => 1, size => 1 },
);
__PACKAGE__->set_primary_key("id");
__PACKAGE__->has_many(
  "graft_failures",
  "ClinStudy::ORM::GraftFailure",
  { "foreign.transplant_id" => "self.id" },
);
__PACKAGE__->belongs_to(
  "hospitalisation_id",
  "ClinStudy::ORM::Hospitalisation",
  { id => "hospitalisation_id" },
);
__PACKAGE__->belongs_to(
  "sensitisation_status_id",
  "ClinStudy::ORM::ControlledVocab",
  { id => "sensitisation_status_id" },
);
__PACKAGE__->belongs_to(
  "organ_type_id",
  "ClinStudy::ORM::ControlledVocab",
  { id => "organ_type_id" },
);
__PACKAGE__->belongs_to(
  "reperfusion_quality_id",
  "ClinStudy::ORM::ControlledVocab",
  { id => "reperfusion_quality_id" },
);
__PACKAGE__->belongs_to(
  "donor_type_id",
  "ClinStudy::ORM::ControlledVocab",
  { id => "donor_type_id" },
);


# Created by DBIx::Class::Schema::Loader v0.04006 @ 2009-10-23 13:53:03
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:ggT3h4MZG0tlWjjP/g9FTg


# You can replace this text with custom content, and it will be preserved on regeneration

# Custom has_many so that we track the cascade_delete behaviour of the
# database correctly (D::C::Schema::Loader doesn't do this yet). These
# relationships replace the autogenerated ones above, and the latter
# can be deleted when we're finally done with D::C::S::L). FIXME

__PACKAGE__->has_many(
  "graft_failures",
  "ClinStudy::ORM::GraftFailure",
  { "foreign.transplant_id" => "self.id" },
  { "cascade_delete"        => 0 },
);

1;
