package ClinStudy::ORM::AssayBatch;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("assay_batch");
__PACKAGE__->add_columns(
  "id",
  { data_type => "INT", default_value => undef, is_nullable => 0, size => 11 },
  "date",
  { data_type => "DATE", default_value => undef, is_nullable => 0, size => 10 },
  "name",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 0,
    size => 31,
  },
  "operator",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => 255,
  },
  "platform_id",
  { data_type => "INT", default_value => undef, is_nullable => 0, size => 11 },
);
__PACKAGE__->set_primary_key("id");
__PACKAGE__->add_unique_constraint("name", ["name"]);
__PACKAGE__->has_many(
  "assays",
  "ClinStudy::ORM::Assay",
  { "foreign.assay_batch_id" => "self.id" },
);
__PACKAGE__->belongs_to(
  "platform_id",
  "ClinStudy::ORM::ControlledVocab",
  { id => "platform_id" },
);


# Created by DBIx::Class::Schema::Loader v0.04006 @ 2010-02-13 17:23:27
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:BJP4w64uIDuYTrqfv9eLWg


# Custom has_many so that we track the cascade_delete behaviour of the
# database correctly (D::C::Schema::Loader doesn't do this yet). These
# relationships replace the autogenerated ones above, and the latter
# can be deleted when we're finally done with D::C::S::L). FIXME

__PACKAGE__->has_many(
  "assays",
  "ClinStudy::ORM::Assay",
  { "foreign.assay_batch_id" => "self.id" },
  { "cascade_delete"     => 0 },
);

1;
