package ClinStudy::ORM::PriorGroup;

# Created by DBIx::Class::Schema::Loader
# DO NOT MODIFY THE FIRST PART OF THIS FILE

use strict;
use warnings;

use base 'DBIx::Class::Core';


=head1 NAME

ClinStudy::ORM::PriorGroup

=cut

__PACKAGE__->table("prior_group");

=head1 ACCESSORS

=head2 id

  data_type: 'integer'
  is_auto_increment: 1
  is_nullable: 0

=head2 type_id

  data_type: 'integer'
  is_foreign_key: 1
  is_nullable: 0

=head2 name

  data_type: 'varchar'
  is_nullable: 0
  size: 255

=cut

__PACKAGE__->add_columns(
  "id",
  { data_type => "integer", is_auto_increment => 1, is_nullable => 0 },
  "type_id",
  { data_type => "integer", is_foreign_key => 1, is_nullable => 0 },
  "name",
  { data_type => "varchar", is_nullable => 0, size => 255 },
);
__PACKAGE__->set_primary_key("id");
__PACKAGE__->add_unique_constraint("name", ["name", "type_id"]);

=head1 RELATIONS

=head2 patient_prior_groups

Type: has_many

Related object: L<ClinStudy::ORM::PatientPriorGroup>

=cut

__PACKAGE__->has_many(
  "patient_prior_groups",
  "ClinStudy::ORM::PatientPriorGroup",
  { "foreign.prior_group_id" => "self.id" },
  {},
);

=head2 type_id

Type: belongs_to

Related object: L<ClinStudy::ORM::ControlledVocab>

=cut

__PACKAGE__->belongs_to(
  "type_id",
  "ClinStudy::ORM::ControlledVocab",
  { id => "type_id" },
);


# Created by DBIx::Class::Schema::Loader v0.07000 @ 2010-07-29 13:19:23
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:6QLrKs22fSu8S+hjDKrKUw


# You can replace this text with custom content, and it will be preserved on regeneration

# This cascading delete is only allowed from the patient, not the
# group.
__PACKAGE__->has_many(
  "patient_prior_groups",
  "ClinStudy::ORM::PatientPriorGroup",
  { "foreign.prior_group_id" => "self.id" },
  { "cascade_delete"   => 0 },
);

# Many-to-many relationships are not yet autogenerated by
# DBIx::Class::Schema::Loader. We add them here:
__PACKAGE__->many_to_many(
    "patients" => "patient_prior_groups", "patient_id",
  { "cascade_delete"   => 0 },
);

1;
